---
# USAGE: ansible-playbook deploy-playbook.yaml -e "deployment_environment=development"
# TESTING - Add testing=true to clean up your resources
#### USAGE: ansible-playbook test-playbook.yaml -e "deployment_environment=development"
#### POSSIBLE STATE VARS
#   - network_state

- hosts: localhost
  gather_facts: yes

  tasks:
    - name: "Import the values file for the {{ deployment_environment }} environment"
      include_vars:
        file: "/opt/ansible/environments/{{ deployment_environment }}/values.yaml"

    - name: "Deploy Infrastructure"
      include_role:
        name: infrastructure



    #-----------CLEAN UP IF CLEAN UP TRUE---------------------

    - name: "Destroy Infrastructure"
      include_role:
        name: infrastructure
      vars:
        network_state: absent
      when: testing == "true"