---


- name: "Find the webserver nsg"
  ec2_group_info:
    filters:
      group-name: 
        - "webserver"
    region: "{{ global_values.region }}"
  register: nsg_group_result

- name: "Deploy ec2 instance as temp web host"
  ec2_instance:
    image_id: "{{ values.ec2.webserver.ami }}"
    instance_initiated_shutdown_behavior: stop
    instance_type: "{{ values.ec2.webserver.instance_type }}"
    key_name: skodaice_key
    name: "{{ values.ec2.webserver.name }}"
    network:
      assign_public_ip: true
    region: "{{ values.ec2.webserver.region }}"
    security_group: default
    tags: "{{ values.ec2.webserver.tags }}"
    vpc_subnet_id: "{{ public_subnet_info.subnets[0].id }}"
  register: ec2_results

- name: Debug ec2 at v 1
  debug:
    var: ec2_results
    verbosity: 1

- name: Add instnace to elb
  ec2_elb:
    instance_id: "{{ ec2_results.instance_ids[0] }}"
    ec2_elbs: "{{ elb_results.elb.name }}"
    region: "{{ global_values.region }}"
    state: present
