

global_values:
  region: "us-east-2"

values:
  vpc:
    cidr_block: 
      - "10.0.0.0/28"
      - "172.2.0.0/24"
    name: "skodaice_vpc"
    region: "{{ global_values.region }}"
    tags:
      deployment_language: "ansible"
      purpose: "website" 
    tenancy: default

  subnets:
    database:
      cidr: "172.2.0.0/24"
      region: "{{ global_values.region }}"
      tags:
        deployment_language: "ansible"
        name: database_subnet
        purpose: "database"

  nsgs:
    admin_home:
      name: "admin_home_access"
      description: "Allow the admin access from home"
      region: "{{ global_values.region }}"
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: "174.19.18.52/32"
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: "174.19.18.52/32"
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: "174.19.18.52/32"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "174.19.18.52/32"
      tags:
        deployment_language: "ansible"
        name: database_subnet
        purpose: "database"

  s3:
    artifacts:
      name: skodaice-artifacts
      mode: create
      permission: private
        